<div class="mx-auto">
  <div class="loadingio-spinner-bars-nq4q5u6dq7r"><div class="ldio-x2uulkbinbj">
<div></div><div></div><div></div><div></div>
</div></div>
<style type="text/css">
@keyframes ldio-x2uulkbinbj {
  0% { opacity: 1 }
  50% { opacity: .5 }
  100% { opacity: 1 }
}
.ldio-x2uulkbinbj div {
  position: absolute;
  width: 24px;
  height: 96px;
  top: 72px;
  animation: ldio-x2uulkbinbj 1s cubic-bezier(0.5,0,0.5,1) infinite;
}.ldio-x2uulkbinbj div:nth-child(1) {
  transform: translate(36px,0);
  background: #009966;
  animation-delay: -0.6s;
}.ldio-x2uulkbinbj div:nth-child(2) {
  transform: translate(84px,0);
  background: #009966;
  animation-delay: -0.4s;
}.ldio-x2uulkbinbj div:nth-child(3) {
  transform: translate(132px,0);
  background: #009966;
  animation-delay: -0.2s;
}.ldio-x2uulkbinbj div:nth-child(4) {
  transform: translate(180px,0);
  background: #009966;
  animation-delay: -1s;
}
.loadingio-spinner-bars-nq4q5u6dq7r {
  width: 240px;
  height: 240px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-x2uulkbinbj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-x2uulkbinbj div { box-sizing: content-box; }
/* [ldio] generated by https://loading.io */
</style>
</div>